spring.application.name=biblioteca

# Configuração do banco H2 (em memória, para desenvolvimento)
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console do H2 (acessível via navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate: cria/atualiza as tabelas automaticamente a partir das entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true